### ISSUE TITLE
npm package js version?

### ISSUE THREAD

**Issue by radames** [LingDong-/skeleton-tracing#3]
hi, this project is very cool! thanks for all the work.

Are you planning to publish the js version as an npm package?
I'd be happy to help craft something if you don't have the time.

Cheers

**Comment by LingDong-** [comment]
Sounds great! If you could help craft something I'd be more than happy to accept it :) Otherwise I also can figure it out when I have some time.

Thanks a lot!

**Comment by radames** [comment]
cool! I'm trying testing out your emscripten compile script using a docker file so the build steps can be described in the repo. I'm not sure if that is necessary, but sounds fun! I'm following some ideas from https://developers.google.com/web/updates/2019/01/emscripten-npm
The npm package can be described in inside your folders **skeleton-tracing/wasm/** **skeleton-tracing/js** but they could be in a different repository. I'll see what's more practical. cheers
