### ISSUE TITLE
crashes, when calling `trace()` a second time

### ISSUE THREAD

**Issue by freder** [LingDong-/skeleton-tracing#9]
when I duplicate [line 10 in the example](https://github.com/LingDong-/skeleton-tracing/blob/master/swig/example.py#L10) the program crashes:

```
python3(10300,0x109f735c0) malloc: *** error for object 0x15c53e000: pointer being freed was not allocated
python3(10300,0x109f735c0) malloc: *** set a breakpoint in malloc_error_break to debug
./compile.sh: line 8: 10300 Abort trap: 6           python3 example.py
```

**Comment by freder** [comment]
not super well versed in C, but removing https://github.com/LingDong-/skeleton-tracing/blob/master/swig/trace_skeleton.c#L631 seems to do it.

**Comment by LingDong-** [comment]
Thanks for spotting the error! I can reproduce this crash. I'm guessing that this is probably because the memory of the image array is managed by python, and got gc'ed already. I've commented out the line in this commit: 607373b69c32f76088f8005ee357ba2dea2b89ce

**Comment by freder** [comment]
yeah, it seems like that's what is happening.
